version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: parking
      POSTGRES_USER: parkinguser
      POSTGRES_PASSWORD: securepass
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./app
    container_name: django_app
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      DATABASE: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      COLLECT_STATIC: 1
    expose:
      - "8000"

  nginx:
    image: nginx:1.25
    container_name: nginx_proxy
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

volumes:
  postgres_data: