version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: parking
      POSTGRES_USER: parkinguser
      POSTGRES_PASSWORD: securepass
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./app
    container_name: django_app
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      DATABASE: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      COLLECT_STATIC: 1
    env_file:
      - .env
    expose:
      - "8000"
    entrypoint: ["/app/entrypoint.sh"]

  nginx:
    image: nginx:1.25
    container_name: nginx_proxy
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    restart: always


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c"
    command: >
      "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done"

  celery_worker:
    build:
      context: ./app
    container_name: celery_worker
    command: celery -A backend worker --loglevel=info
    depends_on:
      - backend
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=django-db
    volumes:
      - ./app:/app

  celery_beat:
    build:
      context: ./app
    container_name: celery_beat
    command: celery -A backend beat --loglevel=info
    depends_on:
      - backend
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=django-db
    volumes:
      - ./app:/app

  redis:
    image: redis:6
    container_name: redis
    command: ["redis-server", "--replicaof", "no", "one"]
    expose:
      - "6379"

volumes:
  postgres_data: