# Generated by Django 5.1.7 on 2025-03-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsessionmodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
