# Generated by Django 5.1.7 on 2025-04-02 14:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingsessionmodel_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsessionmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
