# Generated by Django 5.1.7 on 2025-04-12 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parkingarea_cameraconfiguration_parkingevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsessionmodel',
            name='parking_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_sessions', to='parking.parkingarea'),
        ),
    ]
