# Generated by Django 5.1.7 on 2025-04-26 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkingsessionmodel_parking_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraconfiguration',
            name='is_for_taxi',
            field=models.BooleanField(default=False, help_text='Is this camera for taxi parking'),
        ),
        migrations.CreateModel(
            name='TaxiEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('IN', 'Entering'), ('OUT', 'Exiting')], max_length=3)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('parking_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_events', to='parking.parkingarea')),
            ],
        ),
    ]
