# Generated by Django 5.1.7 on 2025-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_cameraconfiguration_is_for_taxi_taxievent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraconfiguration',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingarea',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
