# Generated by Django 5.1.7 on 2025-04-26 14:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0006_cameraconfiguration_is_for_taxi_taxievent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 4, 26, 14, 52, 11, 853595, tzinfo=datetime.timezone.utc))),
                ('arrival_reason', models.CharField(choices=[('pick_up', 'Pick Up'), ('drop', 'Drop')], max_length=20)),
                ('parking_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingarea')),
            ],
        ),
    ]
