# Generated by Django 5.1.7 on 2025-04-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentattempt_receipt_alter_payment_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('KASSA24', 'Kassa24'), ('KASPI', 'Kaspi'), ('HALYK', 'Halyk Bank')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='provider',
            field=models.CharField(choices=[('KASSA24', 'Kassa24'), ('KASPI', 'Kaspi'), ('HALYK', 'Halyk Bank')], max_length=30),
        ),
    ]
